# fly.toml app configuration file generated for small-feather-2413 on 2023-10-24T23:24:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "small-feather-2413"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
